project:
  type: book
  output-dir: "."

book:
  title: "Stats with Clojure"
  search: true
  sidebar:
    style: "floating"
    search: true
  chapters:
    - part: "Getting Started"
      chapters:
        - text: "Index"
          file: index.qmd
        - text: "About This Book"
          file: about_this_book.qmd
    - part: "Tooling"
      chapters:
        - text: "Setting up VS Code"
          file: setting_up_vscode.qmd
    - part: "Getting your feet wet"
      chapters:
        - text: "Start with Clay"
          file: start_with_clay.qmd
    - part: "Noj and other libraries"
      chapters:
        - text: "Plotly"
          file: plotly.qmd
    - part: "Visualizations"
      chapters:
        - text: "Visualizations"
          file: visualizations.qmd
    - part: "Statistical Terms"
      chapters:
        - text: "Statistics Overview"
          file: statistics.qmd
        - text: "Sample and Population"
          file: sample_and_population.qmd
        - text: "Element"
          file: element.qmd
    - part: "Random Number Generator"
      chapters:
        - text: "Random Number Generator"
          file: random_number_generator.qmd
    - part: "Central Tendencies"
      chapters:
        - text: "Mean"
          file: mean.qmd
        - text: "Median"
          file: median.qmd
        - text: "Mode"
          file: mode.qmd
    - part: "Variability"
      chapters:
        - text: "Range"
          file: stats_range.qmd
        - text: "Gini Coefficient"
          file: gini_coefficient.qmd
    - part: "Project"
      chapters:
        - text: "Chennai Rainfall Analysis"
          file: analysis_of_chennai_rainfall.qmd

format:
  html:
    theme: quarto
    toc: true
    toc-depth: 4
    number-sections: true
