---
format:
  html: {toc: true, toc-depth: 4, theme: quarto}
title: Stats with Clojure
author: Scicloj Team

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script><script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" type="text/javascript"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.20.0/plotly.min.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns plotly
  (:require [scicloj.tableplot.v1.plotly :as plotly]))
```
:::



# Scatter Plot


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "scatter"
          :mode "markers"}]})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"scatter","mode":"markers"}], {}, {});</script></div>
```



## Without markers


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "scatter"}]})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"scatter"}], {}, {});</script></div>
```



## A plot without any configuration


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]}]})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6]}], {}, {});</script></div>
```



## Bar Chart


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"}]})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar"}], {}, {});</script></div>
```




a pie chart needs labels and values, not x and y


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:labels ["A" "B" "C"]
          :values [10 20 30]
          :type "pie"}]})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"labels":["A","B","C"],"values":[10,20,30],"type":"pie"}], {}, {});</script></div>
```



# Customizing the plot


## Specifying color


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"
          :marker {:color "red"}}]})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar","marker":{"color":"red"}}], {}, {});</script></div>
```



## Add title


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"
          :marker {:color "red"}}]
  :layout {:title "My Bar Chart"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar","marker":{"color":"red"}}], {"title":"My Bar Chart"}, {});</script></div>
```



## x and y labels


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"
          :marker {:color "red"}}]
  :layout {:title "My Bar Chart"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar","marker":{"color":"red"}}], {"title":"My Bar Chart","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```



# Mult bar chart


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"
          :marker {:color "red"}}
         {:x [1 2 3]
          :y [6 5 4]
          :type "bar"
          :marker {:color "blue"}}]
  :layout {:title "My Bar Chart"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar","marker":{"color":"red"}},{"x":[1,2,3],"y":[6,5,4],"type":"bar","marker":{"color":"blue"}}], {"title":"My Bar Chart","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```


Multi bar chart without markers


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"}
         {:x [1 2 3]
          :y [6 5 4]
          :type "bar"}]
  :layout {:title "My Bar Chart"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar"},{"x":[1,2,3],"y":[6,5,4],"type":"bar"}], {"title":"My Bar Chart","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```



# Stacked bar chart


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3]
          :y [4 5 6]
          :type "bar"
          :marker {:color "red"}}
         {:x [1 2 3]
          :y [6 5 4]
          :type "bar"
          :marker {:color "blue"}}]
  :layout {:title "My Bar Chart"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}
           :barmode "stack"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[4,5,6],"type":"bar","marker":{"color":"red"}},{"x":[1,2,3],"y":[6,5,4],"type":"bar","marker":{"color":"blue"}}], {"title":"My Bar Chart","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"},"barmode":"stack"}, {});</script></div>
```



# Horizontal bar chart


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [4 5 6]
          :y [1 2 3]
          :type "bar"
          :orientation "h"  ;; <-- this makes it horizontal
          :marker {:color "red"}}]
  :layout {:title "My Bar Chart"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[4,5,6],"y":[1,2,3],"type":"bar","orientation":"h","marker":{"color":"red"}}], {"title":"My Bar Chart","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```



# Line charts with different dash styles


::: {.sourceClojure}
```clojure
(def trace1
  {:x [1 2 3 4 5] :y [6 8 7 8 6]
   :mode "lines" :name "dashdot"
   :line {:dash "dashdot" :width 4}})
```
:::



::: {.sourceClojure}
```clojure
(def trace2
  {:x [1 2 3 4 5] :y [11 13 12 13 11]
   :mode "lines" :name "Solid"
   :line {:dash "solid" :width 4}})
```
:::



::: {.sourceClojure}
```clojure
(def trace3
  {:x [1 2 3 4 5] :y [16 18 17 18 16]
   :mode "lines" :name "dot"
   :line {:dash "dot" :width 4}})
```
:::



::: {.sourceClojure}
```clojure
(def layout
  {:title "Line Dash Styles"
   :xaxis {:range [0.75 5.25] :autorange false}
   :yaxis {:range [0 18.5] :autorange false}
   :legend {:y 0.5 :traceorder "reversed" :font {:size 16}}
   :margin {:t 50}})
```
:::



::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [trace1 trace2 trace3]
  :layout layout})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"mode":"lines","name":"dashdot","line":{"dash":"dashdot","width":4}},{"x":[1,2,3,4,5],"y":[11,13,12,13,11],"mode":"lines","name":"Solid","line":{"dash":"solid","width":4}},{"x":[1,2,3,4,5],"y":[16,18,17,18,16],"mode":"lines","name":"dot","line":{"dash":"dot","width":4}}], {"title":"Line Dash Styles","xaxis":{"range":[0.75,5.25],"autorange":false},"yaxis":{"range":[0,18.5],"autorange":false},"legend":{"y":0.5,"traceorder":"reversed","font":{"size":16}},"margin":{"t":50}}, {});</script></div>
```



# Area chart


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3 4 5]
          :y [6 8 7 8 6]
          :mode "lines"
          :fill "tozeroy"
          :line {:color "blue" :width 0.5}}]
  :layout {:title "Area Chart"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"mode":"lines","fill":"tozeroy","line":{"color":"blue","width":0.5}}], {"title":"Area Chart"}, {});</script></div>
```



# Stacked area chart


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3 4 5]
          :y [6 8 7 8 6]
          :mode "lines"
          :fill "tonexty"
          :line {:color "blue" :width 0.5}}
         {:x [1 2 3 4 5]
          :y [11 13 12 13 11]
          :mode "lines"
          :fill "tonexty"
          :line {:color "red" :width 0.5}}]
  :layout {:title "Stacked Area Chart"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"mode":"lines","fill":"tonexty","line":{"color":"blue","width":0.5}},{"x":[1,2,3,4,5],"y":[11,13,12,13,11],"mode":"lines","fill":"tonexty","line":{"color":"red","width":0.5}}], {"title":"Stacked Area Chart"}, {});</script></div>
```



## Stacked area chart with multiple traces


::: {.sourceClojure}
```clojure
(def traces
  [{:x [1 2 3] :y [2 1 4] :stackgroup "one"}
   {:x [1 2 3] :y [1 1 2] :stackgroup "one"}
   {:x [1 2 3] :y [3 0 2] :stackgroup "one"}])
```
:::



::: {.sourceClojure}
```clojure
(plotly/plot
 {:data traces
  :layout {:title "My Awesome Stacked Chart"
           :margin {:t 50 :l 50}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3],"y":[2,1,4],"stackgroup":"one"},{"x":[1,2,3],"y":[1,1,2],"stackgroup":"one"},{"x":[1,2,3],"y":[3,0,2],"stackgroup":"one"}], {"title":"My Awesome Stacked Chart","margin":{"t":50,"l":50}}, {});</script></div>
```



# Scatter plot with different marker colors


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3 4 5]
          :y [6 8 7 8 6]
          :mode "markers"
          :marker {:color ["red" "green" "blue" "orange" "purple"]
                   :size 10}}]
  :layout {:title "Scatter Plot with Different Marker Colors"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"mode":"markers","marker":{"color":["red","green","blue","orange","purple"],"size":10}}], {"title":"Scatter Plot with Different Marker Colors"}, {});</script></div>
```



# Scatter plot with different marker sizes


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3 4 5]
          :y [6 8 7 8 6]
          :mode "markers"
          :marker {:size [10 20 30 40 50]}}]
  :layout {:title "Scatter Plot with Different Marker Sizes"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"mode":"markers","marker":{"size":[10,20,30,40,50]}}], {"title":"Scatter Plot with Different Marker Sizes"}, {});</script></div>
```



# Scatter plot with lines and markers


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3 4 5]
          :y [6 8 7 8 6]
          :mode "markers+lines"
          :marker {:color "red" :size 10}
          :line {:color "red" :width 2}}]
  :layout {:title "Scatter Plot with Lines"}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"mode":"markers+lines","marker":{"color":"red","size":10},"line":{"color":"red","width":2}}], {"title":"Scatter Plot with Lines"}, {});</script></div>
```



# Box plot


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:y [1 2 3 4 5]
          :type "box"}]
  :layout {:title "Box Plot"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"y":[1,2,3,4,5],"type":"box"}], {"title":"Box Plot","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```



# Histogram


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [6 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 7]
          :type "histogram"}]
  :layout {:title "Histogram"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[6,1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,7],"type":"histogram"}], {"title":"Histogram","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```



# Heatmap


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:z [[1 20 30]
              [20 1 60]
              [30 60 1]]
          :type "heatmap"}]
  :layout {:title "Heatmap"
           :xaxis {:title "X Axis"}
           :yaxis {:title "Y Axis"}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"z":[[1,20,30],[20,1,60],[30,60,1]],"type":"heatmap"}], {"title":"Heatmap","xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"}}, {});</script></div>
```


3D scatter plot
not working as expected


::: {.sourceClojure}
```clojure
(plotly/plot
 {:data [{:x [1 2 3 4 5]
          :y [6 8 7 8 6]
          :z [1 2 3 4 5]
          :mode "markers"
          :marker {:color "red" :size 10}}]
  :layout {:title "3D Scatter Plot"
           :scene {:xaxis {:title "X Axis"}
                   :yaxis {:title "Y Axis"}
                   :zaxis {:title "Z Axis"}}}})
```
:::



```{=html}
<div style="height:auto;width:100%;"><script>Plotly.newPlot(document.currentScript.parentElement, [{"x":[1,2,3,4,5],"y":[6,8,7,8,6],"z":[1,2,3,4,5],"mode":"markers","marker":{"color":"red","size":10}}], {"title":"3D Scatter Plot","scene":{"xaxis":{"title":"X Axis"},"yaxis":{"title":"Y Axis"},"zaxis":{"title":"Z Axis"}}}, {});</script></div>
```



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/scicloj/stats_with_clojure/blob/main/notebooks/plotly.clj">notebooks/plotly.clj</a></small></small></pre></div>
```
